server:
  port: 8089

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  datasource:
    url: jdbc:postgresql://localhost:5432/mainframe
    username: admin
    password: secret123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    liquibase: DEBUG

