version: "3.3"
services:
  app:
    image: ${FRONTEND_IMAGE}
    ports:
      - "9000:3000"
    restart: always
    logging:
      driver: "loki"
      options:
        loki-url: ${LOKI_URL}
        loki-retries: "3"
        loki-batch-size: "400"
        loki-external-labels: |
          app=${JOB_NAME},env=${ENV}

networks: {}
