apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  namespace: {{ .Release.Namespace }}
data:
  config: |
    {{- range $key, $value := .Values.configmaps }}
      {{ printf "%s=%s" $key $value | indent 4 }}
    {{- end }}
   