COPY_TEMPLATE = """       IDENTIFICATION DIVISION.
       PROGRAM-ID. COPYBOOK.

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
{}"""
